apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-ui
  labels:
    app: chatbot-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot-ui
  template:
    metadata:
      labels:
        app: chatbot-ui
    spec:
      containers:
      - name: chatbot-ui
        image: mckaywrigley/chatbot-ui:latest
        ports:
        - containerPort: 80
---
# Assuming you want to expose the chatbot-ui using a Kubernetes Service (NodePort type)

apiVersion: v1
kind: Service
metadata:
  name: chatbot-ui-service
spec:
  selector:
    app: chatbot-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
